### ISSUE TITLE
Can you help me with mobo Asus H510M-A + 13-10105f + XFX RX560D

### ISSUE THREAD

**Issue by ridoamali** [RampagerB/OpenCore-Gigabyte-Aorus-Elite-B460M-10700-RX560-EFI#1]
Can you help me with mobo Asus H510M-A + 13-10105f + XFX RX560D
thanks alot
i appreciate it so much...

**Comment by RampagerB** [comment]
Sorry,I saw you issue just now. I suggest you follow the https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html to config for you own opencore configuration. Or try search "opencore h510" in left top searchbar for other configured EFI shares.
